### ISSUE TITLE
Error in getting results

### ISSUE THREAD

**Issue by coderGtm** [aditya76-git/charusat-unofficial-api#2]
While using `scraper.get_result_data()`, the following error occurs:
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/charusat_scraper/private_api.py", line 169, in get_result_data
    tblStudentResultMst = response.get('tblStudentResultMst', [])[0]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/charusat_scraper/scraper.py", line 309, in get_result_data
    return privateAPI.get_result_data(sem=sem, month_year=month_year)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/charusat_scraper/private_api.py", line 193, in get_result_data
    raise Exception(
Exception: Error Decoding JSON Response
>>> scraper.get_result_data(sem = 4, month_year = "April 2023")
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/charusat_scraper/private_api.py", line 169, in get_result_data
    tblStudentResultMst = response.get('tblStudentResultMst', [])[0]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/charusat_scraper/scraper.py", line 309, in get_result_data
    return privateAPI.get_result_data(sem=sem, month_year=month_year)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/charusat_scraper/private_api.py", line 193, in get_result_data
    raise Exception(
Exception: Error Decoding JSON Response
```

**Comment by coderGtm** [comment]
Upon further investigation, while printing the response received by the api, the following response was received:

```
{'type': 'https://tools.ietf.org/html/rfc7231#section-6.5.13', 'title': 'Unsupported Media Type', 'status': 415, 'traceId': '|700c1c9f-492419907b0c2b6f.'}
```

**Comment by aditya76-git** [comment]
The issue has been fixed 
Thanks for pointing it out...
